name: pyforce-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - IPykernel
  - pip
  - pip:
    - numpy
    - scipy
    - matplotlib
    - pyvista
    - h5py
    - tqdm
    - fluidfoam
    - trame-vtk
    - scikit-learn
    - setuptools>=63.0.0
